/**
 * @module plugins/element-plus
 * 仅注册当前工程实际使用的 Element Plus 组件、指令和图标，避免把完整组件库装入首屏脚本。
 */
import type { App, Component } from 'vue'
import {
  ElAlert,
  ElAside,
  ElAvatar,
  ElButton,
  ElCard,
  ElCheckbox,
  ElCheckboxGroup,
  ElCol,
  ElContainer,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElLink,
  ElLoadingDirective,
  ElMain,
  ElMenu,
  ElMenuItem,
  ElOption,
  ElPagination,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElRate,
  ElResult,
  ElRow,
  ElSegmented,
  ElSelect,
  ElSpace,
  ElStatistic,
  ElStep,
  ElSteps,
  ElSubMenu,
  ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTag,
  ElText,
  ElTimeline,
  ElTimelineItem,
  ElTooltip,
  ElTree,
  ElTreeSelect,
} from 'element-plus'
import {
  ArrowDown,
  ArrowLeft,
  Avatar,
  Box,
  Calendar,
  CircleCheck,
  CircleClose,
  CircleCloseFilled,
  Coin,
  Collection,
  Connection,
  DataAnalysis,
  Delete,
  Document,
  DocumentAdd,
  DocumentChecked,
  EditPen,
  Expand,
  Files,
  Fold,
  GoodsFilled,
  Grid,
  Guide,
  HomeFilled,
  InfoFilled,
  Key,
  List,
  Loading,
  Lock,
  Message,
  MessageBox,
  Monitor,
  Moon,
  Odometer,
  OfficeBuilding,
  Plus,
  Postcard,
  Promotion,
  QuestionFilled,
  Refresh,
  RefreshRight,
  School,
  SetUp,
  Setting,
  ShoppingBag,
  ShoppingCart,
  Star,
  Sunny,
  Switch,
  TakeawayBox,
  Tickets,
  Timer,
  TrendCharts,
  User,
  UserFilled,
  Warning,
  WarningFilled,
} from '@element-plus/icons-vue'

const components: Record<string, Component> = {
  ElAlert, ElAside, ElAvatar, ElButton, ElCard, ElCheckbox, ElCheckboxGroup, ElCol,
  ElContainer, ElDatePicker, ElDescriptions, ElDescriptionsItem, ElDialog, ElDivider,
  ElDrawer, ElDropdown, ElDropdownItem, ElDropdownMenu, ElEmpty, ElForm, ElFormItem,
  ElHeader, ElIcon, ElInput, ElInputNumber, ElLink, ElMain, ElMenu, ElMenuItem, ElOption,
  ElPagination, ElRadio, ElRadioButton, ElRadioGroup, ElRate, ElResult, ElRow, ElSegmented,
  ElSelect, ElSpace, ElStatistic, ElStep, ElSteps, ElSubMenu, ElSwitch, ElTabPane, ElTable,
  ElTableColumn, ElTabs, ElTag, ElText, ElTimeline, ElTimelineItem, ElTooltip, ElTree,
  ElTreeSelect,
}

const icons: Record<string, Component> = {
  ArrowDown, ArrowLeft, Avatar, Box, Calendar, CircleCheck, CircleClose, CircleCloseFilled,
  Coin, Collection, DataAnalysis, Delete, Document, DocumentAdd, DocumentChecked, EditPen,
  Expand, Files, Fold, GoodsFilled, Grid, Guide, HomeFilled, InfoFilled, Key, List,
  Loading, Lock, Message, MessageBox, Monitor, Moon, Odometer, OfficeBuilding, Plus, Postcard,
  Promotion, QuestionFilled, Refresh, RefreshRight, School, SetUp, Setting, ShoppingBag,
  ShoppingCart, Star, Sunny, Switch, TakeawayBox, Tickets, Timer, TrendCharts, User,
  UserFilled, Warning, WarningFilled,
}

// Element Plus 图标库没有 Globe 导出，使用语义最接近的网络连接图标提供统一别名。
icons.Globe = Connection

/** 注册 Element Plus 最小运行集合。 */
export function installElementPlus(app: App) {
  for (const [name, component] of Object.entries({ ...components, ...icons })) {
    app.component(name, component)
  }
  app.directive('loading', ElLoadingDirective)
}
