/**
 * 权限编码到 i18n 翻译键的共享映射。
 * 布局侧边栏和路由守卫共同引用此映射，确保菜单名称和页面标题始终使用 i18n 翻译，
 * 避免因数据库字符集问题导致中文乱码。
 */
export const menuI18nMap: Record<string, string> = {
  'crm': 'common.crmManagement',
  'crm:overview': 'common.crmOverview',
  'crm:lead': 'common.crmLeads',
  'crm:customer': 'common.crmCustomers',
  'crm:contact': 'common.crmContacts',
  'crm:opportunity': 'common.crmOpportunities',
  'crm:activity': 'common.crmActivities',
  'srm': 'common.srmManagement',
  'srm:overview': 'common.srmOverview',
  'srm:supplier': 'common.srmSuppliers',
  'srm:evaluation': 'common.srmEvaluations',
  'srm:risk': 'common.srmRisk',
  'srm:risk:config': 'common.srmRiskConfig',
  'srm:portal': 'common.srmPortal',
  'srm:portal:profile': 'common.srmPortalProfile',
  'srm:portal:evaluation': 'common.srmPortalEvaluation',
  'srm:portal:quotation': 'common.srmPortalQuotation',
  'srm:invite': 'common.srmInvite',
  'procurement': 'common.procurementManagement',
  'procurement:overview': 'common.procurementOverview',
  'procurement:material': 'common.procurementMaterial',
  'procurement:approval-route': 'common.procurementApprovalRoute',
  'procurement:requisition': 'common.procurementRequisition',
  'procurement:rfq': 'common.procurementRfq',
  'procurement:purchase-order': 'common.procurementPurchaseOrder',
  'procurement:goods-receipt': 'common.procurementGoodsReceipt',
  'asset': 'common.assetManagement',
  'asset:overview': 'common.assetOverview',
  'asset:asset': 'common.assetLedger',
  'asset:transfer': 'common.assetTransfer',
  'asset:disposal': 'common.assetDisposal',
  'system': 'common.systemManagement',
  'system:user': 'common.users',
  'system:role': 'common.roles',
  'system:permission': 'common.permissions',
  'system:org': 'common.organizations',
  'system:tenant': 'common.tenants',
  'system:oauth2': 'common.oauth2Clients',
  'system:online': 'common.onlineUsers',
  'system:authrecord': 'common.authRecords',
  'system:auditlog': 'common.auditLogs',
  'system:xssconfig': 'common.xssConfig',
  'base': 'common.baseManagement',
  'base:dict': 'common.dictManagement',
  'base:operlog': 'common.operLogs',
  'monitor': 'common.monitorManagement',
  'base:mqmessage': 'common.mqMessages',
  'job': 'common.jobManagement',
  'job:user-job-type': 'common.userJobTypes',
  'job:system-job': 'common.systemJobs',
  'workflow': 'common.workflowManagement',
  'workflow:model': 'common.workflowModel',
  'workflow:definition': 'common.workflowDefinition',
  'workflow:instance': 'common.workflowInstance',
  'workflow:stats': 'common.workflowStats',
}
